// backend/models/Resume.js
const mongoose = require('mongoose');

const resumeSchema = new mongoose.Schema({
  name: String,
  email: String,
  skills: [String],
  experience: [
    {
      title: String,
      company: String,
      years: Number
    }
  ],
  education: [
    {
      degree: String,
      institution: String,
      year: Number
    }
  ],
  interviewQuestions: [String], // Generated by Gemini API
  uploadedAt: {
    type: Date,
    default: Date.now
  }
});

module.exports = mongoose.model('Resume', resumeSchema);
